version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: creditos_db
    restart: always
    environment:
      POSTGRES_DB: creditos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
